import os
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

"""
Django settings for kdatahub project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Load environment variables
load_dotenv()
env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEBUG = env.bool('DEBUG', default=False)

# In production the key must come from the environment. Falling back to a
# placeholder would let anyone who has read this file forge session cookies
# and password-reset tokens.
SECRET_KEY = env('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-development-only'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable is required when DEBUG is off.'
        )

# Exact hosts only. Wildcards like *.vercel.app cover a namespace anyone can
# deploy into, which would make any stranger's site a trusted origin here.
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
CSRF_TRUSTED_ORIGINS = [
    f'https://{host}' for host in ALLOWED_HOSTS if not host.startswith('.')
]

if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']
    CSRF_TRUSTED_ORIGINS += ['http://localhost:8000', 'http://127.0.0.1:8000']
elif not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS environment variable is required when DEBUG is off, '
        'e.g. ALLOWED_HOSTS=k-datahub.vercel.app'
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'orders',
    'payments',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kdatahub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kdatahub.wsgi.application'


# Database - PostgreSQL for Render, SQLite for local
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if env('DATABASE_URL', default=''):
    DATABASES = {
        'default': env.db(),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles_build' / 'static'
STATICFILES_DIRS = [BASE_DIR / 'static']

_static_backend = (
    'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
    else 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
)


# Media files (Local)
MEDIA_ROOT = BASE_DIR / 'media'

# Paystack Configuration
PAYSTACK_PUBLIC_KEY = env('PAYSTACK_PUBLIC_KEY', default='')
PAYSTACK_SECRET_KEY = env('PAYSTACK_SECRET_KEY', default='')
if not PAYSTACK_SECRET_KEY or not PAYSTACK_PUBLIC_KEY:
    import warnings
    warnings.warn('⚠️ Paystack keys not configured. Payment functionality will be disabled.')

# Firebase Storage (Google Cloud Storage) Configuration for Media Files
USE_FIREBASE_STORAGE = env.bool('USE_FIREBASE_STORAGE', default=False)
if USE_FIREBASE_STORAGE:
    # Firebase Storage (GCS) Settings
    GS_BUCKET_NAME = env('GS_BUCKET_NAME', default='')
    
    # Credentials can be passed as a JSON string in environment variables
    GS_CREDENTIALS_JSON = env('GS_CREDENTIALS', default='')
    if GS_CREDENTIALS_JSON:
        import json
        from google.oauth2 import service_account
        try:
            creds_dict = json.loads(GS_CREDENTIALS_JSON)
            GS_CREDENTIALS = service_account.Credentials.from_service_account_info(creds_dict)
        except Exception as e:
            import warnings
            warnings.warn(f"⚠️ Failed to parse GS_CREDENTIALS JSON: {e}")
            GS_CREDENTIALS = None
            
    _media_backend = 'storages.backends.gcloud.GoogleCloudStorage'
    GS_QUERYSTRING_AUTH = False  # Set to False for public URLs

    # Media files public URL base
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
else:
    # Local Media Storage (Development/Testing)
    MEDIA_URL = '/media/'
    _media_backend = 'django.core.files.storage.FileSystemStorage'

# Django 5.1 removed STATICFILES_STORAGE / DEFAULT_FILE_STORAGE; on 6.0 they are
# silently ignored, so both backends have to be declared here to take effect.
STORAGES = {
    'default': {'BACKEND': _media_backend},
    'staticfiles': {'BACKEND': _static_backend},
}

# Base Domain for Callbacks
BASE_DOMAIN = env('BASE_DOMAIN', default='http://localhost:8000')

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# SMS Configuration
ARKESEL_API_KEY = env('ARKESEL_API_KEY', default='')
SMS_SENDER_ID = env('SMS_SENDER_ID', default='K-DATAHUB')
MANAGER_PHONE = env('MANAGER_PHONE', default='')
ADMIN_PHONE = env('ADMIN_PHONE', default='')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security headers and cookie flags.
# Vercel terminates TLS and forwards the original scheme in this header;
# without it Django sees plain HTTP and SECURE_SSL_REDIRECT would loop.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Shared cache, used by kdatahub.throttle for rate limiting. It has to be
# shared rather than per-process: on Vercel each request may hit a different
# instance, and a per-process counter would never trip.
# Run `python manage.py createcachetable` after deploying.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'kdatahub_cache',
    }
} if env('DATABASE_URL', default='') else {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Logging for Vercel Debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
